TebLocalPlannerROS:

 odom_topic: odom
 map_frame: map 
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.5 #was 0.3
 dt_hysteresis: 0.2 #was 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 2.0 #was 3.0
 feasibility_check_no_poses: 5

 publish_feedback: true
    
 # Robot

 max_vel_x: 0.6 #0.1
 max_vel_x_backwards: 0.3
 max_vel_theta: 0.3 #15deg more or less
 acc_lim_x: 0.1 #was 1.0
 acc_lim_theta: 0.3 #was 0.3
 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
  type: "polygon"


  vertices: [[0.2, -0.2], 
            [-0.2, -0.2], 
            [-0.2, 0.2], 
            [0.2, 0.2]]
          
 # GoalTolerance

 xy_goal_tolerance: 0.15 #was 0.1
 yaw_goal_tolerance: 0.15 #was 0.1
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.20 #was 0.15
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 20 #was 30
 costmap_converter_plugin: "" #costmap_converter::CostmapToPolygonsDBSMCCH"
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5
 inflation_dist: 0.2 #aggiunto
 include_dynamic_obstacles: false

## Configure plugins (namespace move_base/TebLocalPlannerROS/PLUGINNAME)
## The parameters must be added for each plugin separately
#costmap_converter/CostmapToPolygonsDBSMCCH:
#  cluster_max_distance: 0.4
#  cluster_min_pts: 2
#  ransac_inlier_distance: 0.15
#  ransac_min_inliers: 10
#  ransac_no_iterations: 2000
#  ransac_remainig_outliers: 3
#  ransac_convert_outlier_pts: True
#  ransac_filter_remaining_outlier_pts: False
#  convex_hull_min_pt_separation: 0.1

 # Optimization
    
 no_inner_iterations: 3 #5
 no_outer_iterations: 2 #4
 optimization_activate: True
 optimization_verbose: false
 penalty_epsilon: 0.04 #was 0.1, must be less than the lower of the max vel x
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 200.0 #was 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 100 #50
 weight_dynamic_obstacle: 10 # not in use yet
 selection_alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: False #was True, require high computational effort
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4 # reduce this value to reduce the computational effort
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1